// Ledger audit invariants (leo-inspired): the ledger must be a replayable
// state machine. Pure function, zero I/O, unit-testable.
import { isBetter } from "./experiment.ts";
import type { LedgerConfig } from "./types.ts";

const VALID_STATUS = new Set([
  "keep",
  "discard",
  "crash",
  "checks_failed",
  "noop",
]);

/**
 * A ledger row as the auditor sees it. The audit's whole job is to accept
 * possibly-malformed rows, so fields are loose (string status/type allowed).
 */
export interface LedgerRow {
  type?: string;
  run?: number;
  segment?: number;
  status?: string;
  metric?: number | null;
  commit?: string | null;
}

export interface LedgerViolation {
  code: string;
  run?: number;
  message: string;
}

/**
 * Validate a run sequence against the session config. Returns a list of
 * { code, run, message } violations; empty list means the ledger is sound.
 *
 * Invariants:
 * - event order: run numbers contiguous, segment matches config, status valid
 * - baseline first: config must precede any run
 * - keep must improve: every keep after the baseline must beat the current
 *   retained metric (direction-aware)
 * - a discarded improvement needs a failed guard: if a non-keep run's metric
 *   beats the retained value, only `checks_failed` may discard it
 * - commit field: keep rows must carry a commit, non-keep rows must not
 */
export function validateLedger(
  runs: Array<LedgerConfig | LedgerRow>,
  config: Pick<LedgerConfig, "segment" | "direction"> | null | undefined,
): LedgerViolation[] {
  const violations: LedgerViolation[] = [];
  const direction = config?.direction ?? "lower";
  let retained: number | null = null; // current best kept metric (null until first keep)
  let expectedRun = 1;

  const push = (code: string, run: number | undefined, message: string) =>
    violations.push({ code, run, message });

  for (const r of runs) {
    if (r.type === "config") {
      expectedRun = 1; // a new segment restarts run numbering
      continue;
    }

    // ---- event order / baseline ----
    if (r.type !== "run") {
      push("event_order", undefined, `unknown row type ${r.type}`);
      continue;
    }
    if (!VALID_STATUS.has(r.status ?? "")) {
      push("event_order", r.run, `invalid status ${r.status}`);
    }
    if (r.run !== expectedRun) {
      push(
        "event_order",
        r.run,
        `run number ${r.run} != expected ${expectedRun}`,
      );
    }
    expectedRun += 1;
    if (r.segment !== config?.segment) {
      push(
        "event_order",
        r.run,
        `segment ${r.segment} != config segment ${config?.segment}`,
      );
    }

    // ---- commit field consistency (non-keep rows must not carry a commit;
    // keep rows' commit is generated by the tool after the git step) ----
    if (r.status !== "keep" && r.commit) {
      push("commit_field", r.run, "non-keep row must not carry a commit");
    }

    // ---- keep must improve / discard needs failed guard ----
    const metric = r.metric;
    if (metric == null || !Number.isFinite(metric)) {
      if (r.status !== "crash")
        push("event_order", r.run, "non-crash row missing metric");
      continue;
    }

    if (r.status === "keep") {
      if (retained == null) {
        retained = metric; // baseline / first keep
      } else if (!isBetter(metric, retained, direction)) {
        push(
          "keep_without_improvement",
          r.run,
          `keep metric ${metric} does not beat retained ${retained} (${direction})`,
        );
      } else {
        retained = metric;
      }
    } else if (r.status === "noop") {
      // noop does not change the retained value and needs no commit
    } else if (r.status === "crash") {
      // crash metric is null — a crash measured nothing, so it must not
      // touch the retained value (legacy rows carrying 0 are tolerated)
    } else {
      // discard / checks_failed
      if (
        retained != null &&
        isBetter(metric, retained, direction) &&
        r.status !== "checks_failed"
      ) {
        push(
          "discarded_improvement",
          r.run,
          `metric ${metric} beats retained ${retained} but status is ${r.status}, not checks_failed`,
        );
      }
    }
  }

  return violations;
}
